[package]
name = "ketchup"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
lazy_static = "1.5"
limbo = "0.0"
once_cell = "1.21"
tera = "1.20"
tokio = { version = "1.45", features = ["macros", "rt-multi-thread"] }
warp = "0.3"

[[bin]]
name = "ketchup"
path = "src/bin/main.rs"
