service: catchup

provider:
  name: aws
  runtime: provided.al2023
  region: us-east-1
  architecture: arm64
  httpApi:
    cors:
      allowedOrigins:
        - "https://sanket143.me"
        - "https://catchup.sanket143.me"
      allowedHeaders: "*"
      allowedMethods:
        - POST
        - OPTIONS
  environment:
    DATABASE_URL: ''

package:
  artifact: ./target/lambda/catchup/bootstrap.zip

functions:
  graphql:
    handler: catchup
    events:
      - httpApi: "*"

plugins:
  - serverless-scriptable-plugin
custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: cargo lambda build --release --bin lyspace --target aarch64-unknown-linux-gnu --output-format zip

